spring.application.name=customer-service
server.port=8056
spring.datasource.url=jdbc:h2:mem:customers-db
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
spring.ai.mcp.server.protocol=streamable
