spring.application.name=ebank-bot
server.port=8058
spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=true
spring.ai.google.genai.api-key=${AI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.8-flash
